<?php
/**
 * Automatically generated by running "php schema.php redis".
 *
 * You may modify the file, but re-running schema.php against this file will
 * standardize the format without losing your schema changes. It does lose
 * any changes that are not part of schema. Use "note" field to comment on
 * schema itself, and "note" fields are not used in any code generation but
 * only staying within this file.
 *
 * @nolint
 */
///////////////////////////////////////////////////////////////////////////////
// Preamble: C++ code inserted at beginning of ext_{name}.h

DefinePreamble(<<<CPP
#include <redis/hiredis.h>
CPP
);

///////////////////////////////////////////////////////////////////////////////
// Constants
//
// array (
//   'name' => name of the constant
//   'type' => type of the constant
//   'note' => additional note about this constant's schema
// )


///////////////////////////////////////////////////////////////////////////////
// Functions
//
// array (
//   'name'   => name of the function
//   'desc'   => description of the function's purpose
//   'flags'  => attributes of the function, see base.php for possible values
//   'opt'    => optimization callback function's name for compiler
//   'note'   => additional note about this function's schema
//   'return' =>
//      array (
//        'type'  => return type, use Reference for ref return
//        'desc'  => description of the return value
//      )
//   'args'   => arguments
//      array (
//        'name'  => name of the argument
//        'type'  => type of the argument, use Reference for output parameter
//        'value' => default value of the argument
//        'desc'  => description of the argument
//      )
//   'taint_observer' => taint propagation information
//     array (
//       'set_mask' => which bits to set automatically
//       'clear_mask' => which bits to clear automatically
//     )
// )


///////////////////////////////////////////////////////////////////////////////
// Classes
//
// BeginClass
// array (
//   'name'   => name of the class
//   'desc'   => description of the class's purpose
//   'flags'  => attributes of the class, see base.php for possible values
//   'note'   => additional note about this class's schema
//   'parent' => parent class name, if any
//   'ifaces' => array of interfaces tihs class implements
//   'bases'  => extra internal and special base classes this class requires
//   'footer' => extra C++ inserted at end of class declaration
// )
//
// DefineConstant(..)
// DefineConstant(..)
// ...
// DefineFunction(..)
// DefineFunction(..)
// ...
// DefineProperty
// DefineProperty
//
// array (
//   'name'  => name of the property
//   'type'  => type of the property
//   'flags' => attributes of the property
//   'desc'  => description of the property
//   'note'  => additional note about this property's schema
// )
//
// EndClass()

///////////////////////////////////////////////////////////////////////////////

BeginClass(
  array(
    'name'   => "Redis",
    'bases'  => array('Sweepable'),
    'desc'   => "Represents a connection to a set of redis servers.",
    'flags'  =>  HasDocComment,
  ));

DefineFunction(
  array(
    'name'   => "__construct",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
    ),
  ));

DefineFunction(
  array(
    'name'   => "pconnect",
    'desc'   => "Redis::pconnect() is similar to Memcached::set(), but the operation fails if the key already exists on the server.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Boolean,
      'desc'   => "Returns TRUE on success or FALSE on failure. The Memcached::getResultCode() will return Memcached::RES_NOTSTORED if the key already exists.",
    ),
    'args'   => array(
      array(
        'name'   => "host",
        'type'   => String,
        'desc'   => "The key under which to store the value.",
      ),
      array(
        'name'   => "port",
        'type'   => Int32,
        'value'  => "0",
        'desc'   => "The expiration time, defaults to 0. See Expiration Times for more info.",
      ),
       array(
        'name'   => "timeout",
        'type'   => Double,
        'value'  => "0.0",
        'desc'   => "the timeout value",
      ),
    ),
  ));
DefineFunction(
  array(
    'name'   => "connect",
    'desc'   => "Redis::pconnect() is similar to Memcached::set(), but the operation fails if the key already exists on the server.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Boolean,
      'desc'   => "Returns TRUE on success or FALSE on failure. The Memcached::getResultCode() will return Memcached::RES_NOTSTORED if the key already exists.",
    ),
    'args'   => array(
      array(
        'name'   => "host",
        'type'   => String,
        'desc'   => "The key under which to store the value.",
      ),
      array(
        'name'   => "port",
        'type'   => Int32,
        'value'  => "0",
        'desc'   => "The expiration time, defaults to 0. See Expiration Times for more info.",
      ),
       array(
        'name'   => "timeout",
        'type'   => Double,
        'value'  => "0.0",
        'desc'   => "the timeout value",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "select",
    'desc'   => "Switches to a given database.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Boolean,
      'desc'   => "TRUE in case of success, FALSE in case of failure.",
    ),
    'args'   => array(
      array(
        'name'   => "dbindex",
        'type'   => Int32,
        'desc'   => "dbindex, the database number to switch to.",
      ),
    ),
  ));
  
DefineFunction(
  array(
    'name'   => "get",
    'desc'   => "Get the value related to the specified key",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "String or Bool: If key didn't exist, FALSE is returned. Otherwise, the value related to this key is returned.",
    ),
    'args'   => array(
      array(
        'name'   => "key",
        'type'   => String,
        'desc'   => "Array containing the list of the keys",
      ),
    ),
  ));
DefineFunction(
  array(
    'name'   => "mGet",
    'desc'   => "mutil get keys...",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns the array of found items or FALSE on failure. Use Memcached::getResultCode() if necessary.",
    ),
    'args'   => array(
      array(
        'name'   => "keys",
        'type'   => StringVec,
        'desc'   => "Array containing the list of the keys",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "close",
    'desc'   => "Disconnects from the Redis instance, except when pconnect is used.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns the array of found items or FALSE on failure. Use Memcached::getResultCode() if necessary.",
    ),
  ));  
  
  

EndClass(
);

